version: '3.3'
services:
  speedtest:
     container_name: speedtest
     image: henrywhitaker3/speedtest-tracker
     volumes:
       - /mnt/iron/test:/config
     environment:
       - TZ="Europe/Berlin"
       - PGID=${PGID:-1000}
       - PUID=${PUID:-100}
       - OOKLA_EULA_GDPR=true
       - AUTH=true
     ports:
       - "9044:80"
     logging:
       driver: "json-file"
       options:
           max-file: "10"
           max-size: "200k"
     restart: unless-stopped
